# Generated by Django 4.2.9 on 2026-05-29 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('ensino_medio', 'Ensino Médio'), ('fundamental', 'Ensino Fundamental'), ('superior', 'Superior')], max_length=20)),
                ('serie_ano', models.CharField(blank=True, max_length=20)),
                ('turno', models.CharField(blank=True, choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=15)),
                ('num_alunos_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('config_ia', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluida_em', models.DateTimeField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
