# Generated by Django 4.2.9 on 2026-05-29 00:50

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('tipo_fonte', models.CharField(choices=[('arquivo', 'Arquivo'), ('texto_colado', 'Texto colado')], max_length=15)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=app.models.ementa_upload_path)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255)),
                ('arquivo_tipo', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=5)),
                ('arquivo_tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('texto_colado', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ementas', to='app.disciplina')),
            ],
            options={
                'verbose_name': 'Ementa',
                'verbose_name_plural': 'Ementas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
