# Generated by Django 5.2.15 on 2026-06-26 00:31

import app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_prova'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infografico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=app.models.infografico_upload_path)),
                ('texto_resumo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerado', 'Gerado'), ('erro', 'Erro')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ementa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infografico', to='app.ementa')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infograficos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infográfico',
                'verbose_name_plural': 'Infográficos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
