# Generated by Codex on 2026-06-26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_infografico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFlashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_recebida', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_flashcard', to='app.disciplina')),
                ('ementa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_flashcard', to='app.ementa')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_flashcard', to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(related_name='lotes_flashcard', to='app.questao')),
            ],
            options={
                'verbose_name': 'Lote de flashcard',
                'verbose_name_plural': 'Lotes de flashcard',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='loteflashcard',
            index=models.Index(fields=['professor', '-criado_em'], name='lote_f_prof_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='loteflashcard',
            index=models.Index(fields=['disciplina', '-criado_em'], name='lote_f_disc_criado_idx'),
        ),
    ]
