# Generated by Django 5.2.15 on 2026-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_loteflashcard'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loteflashcard',
            constraint=models.UniqueConstraint(condition=models.Q(('ementa__isnull', False)), fields=('ementa',), name='unique_lote_flashcard_por_ementa'),
        ),
    ]
